OHC.EAMI.WebUI/Controllers/ManageSystemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using AutoMapper;
using OHC.EAMI.Common;
using OHC.EAMI.Common.ServiceInvoke;
using OHC.EAMI.CommonEntity;
using OHC.EAMI.WebUI.Data;
using OHC.EAMI.WebUI.Filters;
using OHC.EAMI.WebUI.Models;

namespace OHC.EAMI.WebUI.Controllers
{
    [EAMIAuthentication]
    [AuthorizeResource(EAMIRole.ADMINISTRATOR, EAMIRole.PROCESSOR, EAMIRole.SUPERVISOR)]
    public class ManageSystemsController : BaseController
    {
        private readonly WcfServiceInvoker _wcfService;
        private readonly ServiceInjector _serviceInjector;
        private readonly IMapper _mapper;
        enum Environment { Test = 1, Stage = 2, Prod = 3 }
        enum PaymentType { Warrant = 1, EFT = 2 }

        public ManageSystemsController()
        {
            _wcfService = new WcfServiceInvoker();
            _serviceInjector = new ServiceInjector();
            _mapper = _serviceInjector.InjectService();
        }

        #region Fund: CRUD public functions...

        [AuthorizeResource(EAMIRole.ADMINISTRATOR)]
        [AjaxOnly]
        public ActionResult AddNewFund(int systemId, string systemCode)
        {
            EAMIFundModel model = new EAMIFundModel();
            model.System_ID = systemId;
            model.System_Code = systemCode;
            return PartialView("Fund/AddNewFund", model);
        }

        /// <summary>
        /// POST: Fund/Create
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        [AjaxOnly]
        public ActionResult CreateFund(EAMIFundModel fundInput)
        {
            string status = string.Empty;
            string message = string.Empty;

            if (ModelState.IsValid)
            {
                Fund fundToBeCreated = _mapper.Map<Fund>(fundInput);
                fundToBeCreated.CreatedBy = User.Identity.Name;
                fundToBeCreated.IsActive = true;

                CommonStatus cs = _wcfService.InvokeService<IEAMIWebUIDataService, CommonStatus>
                                        (svc => svc.AddEAMIFund(fundToBeCreated));

                if (cs.Status)
                {
                    status = "OK";
                    message = cs.GetCombinedMessage();
                }
                else
                {
                    status = "ERROR";
                    message = cs.GetCombinedMessage();
                }
            }

            var jsonData = new
            {
                status = status,
                message = message
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// GET: Fund
        /// </summary>
        /// <param name="includeInactive">This flag controls the UI and Reports data to be shown.
        /// The same Stored Proc will show on Active Funds on UI and All Active + InActive funds in reports.
        /// </param>
        /// <returns></returns>
        [AuthorizeResource(EAMIRole.ADMINISTRATOR)]
        [AjaxOnly]
        public ActionResult ViewFunds(int systemID, bool includeInactive = false)
        {
            //Initialize the mapper
            var lstFunds = AdministrationQueries.GetAllFunds(includeInactive, systemID);
            ViewBag.SystemId = systemID;
            ViewBag.SystemCode = GetSystemCode(systemID);

            List<EAMIFundModel> fundModelDto = _mapper.Map<List<Fund>, List<EAMIFundModel>>(lstFunds);

            return PartialView("Fund/ViewFunds", fundModelDto);
        }

        /// <summary>
        /// Edit a fund for a given systemID and Fund ID
        /// </summary>
        /// <param name="fundID">fund ID</param>
        /// <param name="systemID">system ID</param>
        /// <returns></returns>
        [AuthorizeResource(EAMIRole.ADMINISTRATOR)]
        [HttpGet]
        [AjaxOnly]
        public ActionResult EditFund(long fundID, long systemID)
        {
            Fund model = new Fund();
            model = GetFundByID(fundID, systemID);
            model.System_Code = GetSystemCode(systemID);

            EAMIFundModel fundDto = _mapper.Map<EAMIFundModel>(model);
            return PartialView("Fund/EditFund", fundDto);
        }

        /// <summary>
        /// GET: Fund/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AuthorizeResource(EAMIRole.ADMINISTRATOR)]
        [HttpPost]
        [AjaxOnly]
        public ActionResult UpdateFund(EAMIFundModel fundInput, bool isActive)
        {
            string status = string.Empty;
            string message = string.Empty;

            if (ModelState.IsValid)
            {
                Fund fundToBeUpdated = _mapper.Map<Fund>(fundInput);
                fundToBeUpdated.IsActive = isActive;
                fundToBeUpdated.UpdatedBy = User.Identity.Name;

                CommonStatus cs = _wcfService.InvokeService<IEAMIWebUIDataService, CommonStatus>
                                        (svc => svc.UpdateEAMIFund(fundToBeUpdated));

                if (cs.Status)
                {
                    status = "OK";
                    message = cs.GetCombinedMessage();
                }
                else
                {
                    status = "ERROR";
                    message = cs.GetCombinedMessage();
                }
                //ErrorHandlerController.CheckFatalException(cs.Status, cs.IsFatal, cs.GetCombinedMessage());
            }

            var jsonData = new
            {
                status = status,
                message = message
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// GET: Fund/Delete/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AuthorizeResource(EAMIRole.ADMINISTRATOR)]
        [HttpPost]
        [AjaxOnly]
        public ActionResult DeleteFund(EAMIFundModel softDeleteFund, bool isActive)
        {
            string response = string.Empty;

            var result = UpdateFund(softDeleteFund, isActive);
            var jsonData = new
            {
                response = ((JsonResult)result).Data
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Exclusive Payment Type: CRUD public functions...

        [AuthorizeResource(EAMIRole.ADMINISTRATOR)]
        [AjaxOnly]
        public ActionResult AddNewExclusivePmtType(int systemId, string systemCode)
        {
            EAMIExclusivePmtTypeModel model = new EAMIExclusivePmtTypeModel();

            model.System_ID = systemId;
            model.System_Code = systemCode;
            bool includeInactive = false;

            var lstFunds = AdministrationQueries.GetAllFunds(includeInactive, systemId);

            model.Funds = new List<SelectListItem>();
            foreach (var fund in lstFunds)
            {

                model.Funds.Add(new SelectListItem() { Value = fund.Fund_ID.ToString(), Text = fund.Fund_Code + " (" + fund.Fund_Name + ")" });
            }



            return PartialView("ExclusivePmtType/AddNewExclusivePmtType", model);
        }

        /// <summary>
        /// POST: ExclusivePmtType/Create
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        [AjaxOnly]
        public ActionResult CreateExclusivePmtType(EAMIExclusivePmtTypeModel exclusivePmtTypeInput)
        {
            string status = string.Empty;
            string message = string.Empty;

            if (ModelState.IsValid)
            {
                ExclusivePmtType exclusivePmtType = new ExclusivePmtType();
                exclusivePmtType.Exclusive_Payment_Type_Code = exclusivePmtTypeInput.Exclusive_Payment_Type_Code;
                exclusivePmtType.Exclusive_Payment_Type_Name = exclusivePmtTypeInput.Exclusive_Payment_Type_Name;
                exclusivePmtType.Exclusive_Payment_Type_Description = exclusivePmtTypeInput.Exclusive_Payment_Type_Description;


                exclusivePmtType.Fund_ID = exclusivePmtTypeInput.Fund_ID;
                exclusivePmtType.System_ID = exclusivePmtTypeInput.System_ID;

                exclusivePmtType.CreatedBy = User.Identity.Name;
                exclusivePmtType.IsActive = true;

                CommonStatus cs = _wcfService.InvokeService<IEAMIWebUIDataService, CommonStatus>
                                        (svc => svc.AddEAMIExclusivePmtType(exclusivePmtType));

                if (cs.Status)
                {
                    status = "OK";
                    message = cs.GetCombinedMessage();
                }
                else
                {
                    status = "ERROR";
                    message = cs.GetCombinedMessage();
                }
                //ErrorHandlerController.CheckFatalException(cs.Status, cs.IsFatal, cs.GetCombinedMessage());
            }

            var jsonData = new
            {
                status = status,
                message = message
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// GET: ExclusivePmtType
        /// </summary>
        /// <param name="includeInactive">This flag controls the UI and Reports data to be shown.
        /// The same Stored Proc will show on Active Funds on UI and All Active + InActive funds in reports.
        /// </param>
        /// <returns></returns>
        [AuthorizeResource(EAMIRole.ADMINISTRATOR)]
        [AjaxOnly]
        public ActionResult ViewExclusivePmtType(int systemID, bool includeInactive = false)
        {
            var lstExclusivePmtType = AdministrationQueries.GetAllExclusivePmtTypes(includeInactive, systemID);

            ViewBag.SystemId = systemID;

OHC.EAMI.WebUI/Views/ManageSystems/Facesheet/AddNewFacesheetValues.cshtml
@{
    ViewBag.Title = "Add New Fund";
}


@using System.Web.Optimization;
@model OHC.EAMI.WebUI.Models.FacesheetModel

@using (Html.BeginForm("CreateFacesheetValues", "ManageSystems", FormMethod.Post, new { @class = "form-horizontal", role = "form", @ID = "frmAddNewFacesheet", autocomplete = "off" }))
{
<div class="panel-body">
    <div id="dvAddErrorHolder"></div>
    <div class="form-group">
        <div class="col-xs-4">
            <input type="hidden" id="hdnSystemId" value="@Model.System_ID" />
            <div class="form-group">
                <div class="col-xs-4">
                    @Html.HiddenFor(input => input.System_ID, new { @class = "form-control input-sm", id = "hdnSystemID", maxlength = "10" })
                    @Html.HiddenFor(input => input.System_Code, new { @class = "form-control input-sm", id = "hdnSystemCode", maxlength = "10" })
                </div>
            </div>
            @Html.LabelFor(input => input.System_Code, new { @class = "control-label" })<span style="color:red;font-weight:bold"></span>
            @Html.TextBoxFor(input => input.System_Code, new { @class = "form-control input-sm", id = "txtSystemCode", maxlength = "200", @disabled = "disabled" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-4">
            @Html.LabelFor(input => input.Fund_Code, new { @class = "control-label" })<span style="color:red;font-weight:bold">&nbsp;*</span>
            @Html.DropDownListFor(input => input.Fund_Code, new SelectList(Model.List_Funds, "Value", "Text") , new { @class = "form-control input-sm", id = "ddlFundCode" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-4">
            @Html.LabelFor(input => input.Reference_Item, new { @class = "control-label" })<span style="color:red;font-weight:bold">&nbsp;*</span>
            @Html.TextBoxFor(input => input.Reference_Item, new { @class = "form-control input-sm", id = "txtReferenceItem", maxlength = "50" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-4">
            @Html.LabelFor(input => input.Chapter, new { @class = "control-label" })<span style="color:red;font-weight:bold">&nbsp;*</span>
            @Html.TextBoxFor(input => input.Chapter, new { @class = "form-control input-sm", id = "txtChapter", maxlength = "100" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-4">
            @Html.LabelFor(input => input.Element, new { @class = "control-label" })<span style="color:red;font-weight:bold"></span>
            @Html.TextBoxFor(input => input.Element, new { @class = "form-control input-sm", id = "txtChapter", maxlength = "100" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-4">
            @Html.LabelFor(input => input.Program, new { @class = "control-label" })<span style="color:red;font-weight:bold"></span>
            @Html.TextBoxFor(input => input.Program, new { @class = "form-control input-sm", id = "txtProgram", maxlength = "100" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-4">
            @Html.LabelFor(input => input.Description, new { @class = "control-label" })<span style="color:red;font-weight:bold">&nbsp;*</span>
            @Html.TextBoxFor(input => input.Description, new { @class = "form-control input-sm", id = "txtDescription", maxlength = "100" })
        </div>
    </div>
</div>
    <div class="form-group">

    </div>
    <div style="clear:both"></div>
    <div class="form-group" style="margin-top:20px;">
        <div class="col-xs-4">
            <button type="button" onclick="return AddNewFacesheet();" class="btn btn-dhcs-secondary btn-sm" id="btnAddNewFacesheet">Add New</button>&nbsp;
            <button type="button" onclick="return AddNewFacesheetReset();" class="btn btn-dhcs-secondary btn-sm" id="btnAddNewFacesheetReset">Reset</button>&nbsp;
            <button type="button" onclick="return AddNewFacesheetBack();" class="btn btn-dhcs-secondary btn-sm" id="btnAddNewFacesheetBack" style="float:none">Back</button>&nbsp;
        </div>
    </div>
    @*</div>*@
    @*</div>*@
}

<script type="text/javascript">
    var frmValidator = $("#frmAddNewFacesheet").validate({
        errorElement: 'span',
        ignore: ".ignore",
        rules: {
            Reference_Item: {
                required: true,
            },
            Fund_Code: {
                required: true,
            },
            Chapter: {
                required: true,
            },
            Description: {
                required: true,
            },
        },

        // Messages for form validation
        messages: {
            Reference_Item: {
                required: 'Please enter Reference Item',
            },
            Fund_Code: {
                required: 'Please enter Fund Code',
            },
            Chapter: {
                required: 'Please enter Chapter',
            },
            Description: {
                required: 'Please enter Description',
            },
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element);
        }

    });

    function ajaxValidateAddNewFacesheet() {
        return frmValidator.form();
    }

    function AddNewFacesheet() {
        if (!ajaxValidateAddNewFacesheet()) {
            return false;
        }
        else {
            HideFormStatusMessage('frmAddNewFacesheet', 'dvAddErrorHolder');
            var systemID = document.getElementById('hdnSystemID').value;

            //alert(systemID);
            var isSuccess = false;
            $.ajax({
                url: getEAMIAbsoluteUrl('~/ManageSystems/CreateFacesheet'),
                type: 'POST',
                datatype: "html",
                cache: false,
                data: $("#frmAddNewFacesheet").serialize(),
                success: function (data) {
                    var message = "";
                    var status = "";
                    if (data != null) {
                        //undefined in case of some exception. for ex: Session override error
                        if (data.message == undefined || data.status == undefined) {
                            message = "An error occured. Please refresh the screen and try again.";
                            status = false;
                        }
                        else {
                            message = data.message;
                            status = data.status;
                        }
                        wasItAAsuccess = (status == "OK");

                        if (wasItAAsuccess) {
                            setFormStatusMessage('frmAddNewFacesheet', 'dvAddErrorHolder', true, message, 4);
                        }
                        else {
                            setFormStatusMessage('frmAddNewFacesheet', 'dvAddErrorHolder', false, message, 5);
                        }
                    }
                },
                error: function () {
                    setFormStatusMessage('frmAddNewFacesheet', 'dvAddErrorHolder', false, 'An error occured. Please refresh the screen and try again.', 5);
                }
            });
        }
        return false;
    }

    function AddNewFacesheetReset() {

        Clear_Form('frmAddNewFacesheet');
        HideFormStatusMessage('frmAddNewFacesheet', 'dvAddErrorHolder');
        frmValidator.resetForm();
        document.getElementById('txtSystemCode').value = document.getElementById('hdnSystemCode').value;

        return false;
    }

    function AddNewFacesheetBack() {
        $('#divLoadingAnimation').css("display", "block");
        EAMIShowAjaxLoadingContent('divLoadingAnimation_Inner');

        $("#dvMainArea").slideUp(250, function () {
            // Animation complete.
            //EAMIShowAjaxLoadingContent('dvActionArea');
            var systemID = document.getElementById('hdnSystemID').value;
            $('#dvActionArea').slideDown(250, function () {
                $('#dvtab5').load(getEAMIAbsoluteUrl('~/ManageSystems/ViewFacesheetValues?systemID=' + systemID + '&includeInactive=' + false));

                // End Loading... Animation
                $('#divLoadingAnimation_Inner').empty();
                $('#divLoadingAnimation').css("display", "none");
            });
        });

        return false;
    }

</script>

OHC.EAMI.WebUI/Views/ManageSystems/Facesheet/ViewFacesheetValues.cshtml
@{
    ViewBag.Title = "Funds";
}

@using System.Web.Optimization;
@model IList<OHC.EAMI.CommonEntity.FacesheetValues>

@using (Html.BeginForm("ViewFacesheetValues", "ManageSystems", FormMethod.Post, new { @class = "form-horizontal", role = "form", @ID = "frmFacesheetData", autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    @*<div class="panel panel-default">*@
<div class="row" style="margin-bottom:20px;margin-top:20px;">
    <input type="hidden" id="hdnSystemId" value="@ViewBag.SystemId" />
    <input type="hidden" id="hdnSystemCode" value="@ViewBag.SystemCode" />
    <div class="col-xs-12">
        <button type="button" onclick="javascript: return AddFacesheetValue();" class="btn btn-dhcs-secondary btn-md" id="btnAddFacesheetValue" style="float:right;margin-right:10px;">Add New</button>
    </div>
</div>
    <table id="grdFunds" class="table table-striped table-bordered" cellspacing="0" style="width:100%;">
        <thead>
            <tr>
                <th>Fund Code</th>
                <th>Fund Name</th>
                <th>Agency Number</th>
                <th>Agency Name</th>
                <th>Stat Year</th>
                <th>Reference/Item</th>
                @*<th>Fiscal Year</th>*@
                <th>Chapter Value</th>
                <th>Element</th>
                <th>Program</th>
                <th>Description</th>
                <th>Create Date</th>
                <th>Created By</th>
                <th>Update Date</th>
                <th>Updated By</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Fund_Code)</td>
                    <td>@Html.DisplayFor(modelItem => item.Fund_Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Agency_Number)</td>
                    <td>@Html.DisplayFor(modelItem => item.Agency_Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Stat_Year)</td>
                    <td>@Html.DisplayFor(modelItem => item.Reference_Item)</td>
                    @*<td>@Html.DisplayFor(modelItem => item.Fiscal_Year)</td>*@
                    <td>@Html.DisplayFor(modelItem => item.Chapter)</td>
                    <td>@Html.DisplayFor(modelItem => item.Element)</td>
                    <td>@Html.DisplayFor(modelItem => item.Program)</td>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                    <td>@item.CreateDate.ToString("MM'/'dd'/'yyyy")</td>
                    <td>@Html.DisplayFor(modelItem => item.CreatedBy)</td>
                    <td>@(item.UpdateDate.HasValue ? item.UpdateDate.Value.ToString("MM/dd/yyyy") : "")</td>
                    <td>@Html.DisplayFor(modelItem => item.UpdatedBy)</td>
                    <td><a href="#" target="_self" onclick="return EditFacesheetValue(@Html.DisplayFor(modelItem => item.Facesheet_ID), @ViewBag.SystemId, true);">Edit</a></td>
                </tr>
            }
        </tbody>
    </table>
}

<script type="text/javascript">
    var systemId = document.getElementById('hdnSystemId').value;
    var systemCode = document.getElementById('hdnSystemCode').value;

    function AddFacesheetValue() {
       
        $('#divLoadingAnimation').css("display", "block");
        $('#header').css("display", "block");
        EAMIShowAjaxLoadingContent('divLoadingAnimation_Inner');

        $("#dvMainArea").slideUp(250, function () {
            // Animation complete.
            $('#dvActionArea').slideDown(250, function () {
                $('#dvtab5').load(getEAMIAbsoluteUrl('~/ManageSystems/AddNewFacesheet?systemId=' + systemId + '&systemCode=' + systemCode));
                // End Loading... Animation
                $('#divLoadingAnimation_Inner').empty();
                $('#divLoadingAnimation').css("display", "none");
            });
        });

        return false;
    }

    function EditFacesheetValue(fsID, systemId, isActive) {
        $('#divLoadingAnimation').css("display", "block");
        $('#header').css("display", "block");
        EAMIShowAjaxLoadingContent('divLoadingAnimation_Inner');

        $("#dvMainArea").slideUp(250, function () {
            // Animation complete.
            //EAMIShowAjaxLoadingContent('dvActionArea');
            $('#dvActionArea').slideDown(250, function () {
                $('#dvtab5').load(getEAMIAbsoluteUrl('~/ManageSystems/EditFacesheetValues?fsID=' + fsID + '&systemID=' + systemId));

                // End Loading... Animation
                $('#divLoadingAnimation_Inner').empty();
                $('#divLoadingAnimation').css("display", "none");
            });
        });

        return false;
    }
</script>